# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch


# Create random tensor
tensor = torch.randn((7, 7))
tensor.shape, tensor.ndim, tensor

(torch.Size([7, 7]),
 2,
 tensor([[ 0.7948,  0.9634, -0.9965, -0.1175, -0.5661,  0.4254,  0.6366],
         [-0.4071, -0.5704, -0.9989,  0.8098, -0.2425,  1.9512, -1.0042],
         [ 0.8795,  0.5904,  0.7084,  2.2140, -0.6834, -1.4863,  0.4711],
         [ 1.0175,  1.8705,  0.7227, -1.9789, -1.2443, -1.2487,  0.9585],
         [ 0.2245, -0.7886,  0.6431, -0.4280,  1.2174, -0.4915,  0.3661],
         [ 1.1835,  1.1736, -0.0479, -0.4372, -0.1365,  0.0155, -0.9006],
         [-0.7041,  0.0725, -0.8787, -0.3023,  1.0035, -0.2429,  1.2320]]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [10]:
# Create another random tensor
tensor2 = torch.randn((1, 7))

# Perform matrix multiplication
transpose_tensor = tensor2.transpose(1, 0)
display(transpose_tensor.shape)
display(transpose_tensor.ndim)
display(transpose_tensor)
tensorx = torch.matmul(tensor, transpose_tensor)
tensorx

torch.Size([7, 1])

2

tensor([[ 0.1845],
        [ 1.4577],
        [-0.7078],
        [ 0.7613],
        [ 0.4418],
        [ 0.6808],
        [-0.1535]])

tensor([[ 2.1087],
        [ 1.7922],
        [ 0.8208],
        [-0.6506],
        [-1.7421],
        [ 1.7188],
        [ 0.4566]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [14]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor_a = torch.rand((7,7))
tensor_b = torch.rand((1,7))

# Matrix multiply tensors
tensor_c = torch.matmul(tensor_a, tensor_b.transpose(1, 0))
tensor_c, tensor_c.shape, tensor_c.ndim

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]),
 2)

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [16]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)
#Found it here https://pytorch.org/docs/master/generated/torch.cuda.manual_seed.html#torch.cuda.manual_seed


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [17]:
# Set random seed
import torch
torch.cuda.manual_seed(1234) #You can comment one or the other (not both), and the results I get keep being the same
torch.manual_seed(1234)

# Check for access to GPU
display(torch.cuda.is_available())

# Create two random tensors on GPU
tensor_1 = torch.rand((2, 3), device="cuda")
tensor_2 = torch.rand((2, 3), device="cuda")
tensor_1, tensor_2

True

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [18]:
# Perform matmul on tensor_A and tensor_B
tensor_3 = torch.matmul(tensor_1, tensor_2.transpose(1,0))
tensor_3

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [20]:
# Find max
display(torch.max(tensor_3))
display(tensor_3.max())

# Find min
display(torch.min(tensor_3))
display(tensor_3.min())

tensor(0.7668, device='cuda:0')

tensor(0.7668, device='cuda:0')

tensor(0.2786, device='cuda:0')

tensor(0.2786, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [21]:
# Find arg max
display(torch.argmax(tensor_3))
display(tensor_3.argmax())

# Find arg min
display(torch.argmin(tensor_3))
display(tensor_3.argmin())

tensor(1, device='cuda:0')

tensor(1, device='cuda:0')

tensor(0, device='cuda:0')

tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [22]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensorx = torch.rand((1, 1, 1, 10))

# Remove single dimensions
tensory = torch.squeeze(tensorx)

# Print out tensors and their shapes
display(tensorx)
display(tensory)
tensorx.shape, tensory.shape, tensorx.ndim, tensory.ndim

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

(torch.Size([1, 1, 1, 10]), torch.Size([10]), 4, 1)